spring:
  cloud:
    discovery:
      enabled: true
    netflix:
      eureka:
        client:
          serviceUrl:
            defaultZone: { HOST-EUREKA }
  elasticsearch:
    rest:
      username: { USERNAME }
      password: { PASSWORD }
      uris: { HOST-BONSAI-ELASTICSEARCH }
  application:
    name: api-operator
  data:
    elasticsearch:
      repositories:
        enabled: true

api-operator:
  rest:
    base-path: /api/movie
    add-movie: /add
    edit-movie: /{id}
    get-movie: /{id}
    get-movies: /all
    delete-movie: /{id}
    search: /find
