spring:
  cloud:
    discovery:
      enabled: true
    netflix:
      eureka:
        client:
          serviceUrl:
            defaultZone: ${EUREKA}
  elasticsearch:
    rest:
      username: ${ELASTICUSER}
      password: ${ELASTICPASS}
      uris: ${ELASTICHOST}
  application:
    name: api-operator
  data:
    elasticsearch:
      repositories:
        enabled: true

api-operator:
  rest:
    base-path: /api/movie
    add-movie: /add
    edit-movie: /{id}
    get-movie: /{id}
    get-movies: /all
    delete-movie: /{id}
    search: /find
